ALTER TYPE "trace_event_type" ADD VALUE IF NOT EXISTS 'GROQ_QUOTA_WAIT_STARTED';
ALTER TYPE "trace_event_type" ADD VALUE IF NOT EXISTS 'GROQ_QUOTA_RESERVED';
ALTER TYPE "trace_event_type" ADD VALUE IF NOT EXISTS 'PROVIDER_REQUEST_STARTED';
ALTER TYPE "trace_event_type" ADD VALUE IF NOT EXISTS 'PROVIDER_REQUEST_COMPLETED';
ALTER TYPE "trace_event_type" ADD VALUE IF NOT EXISTS 'VERIFICATION_COMPLETED';
ALTER TYPE "trace_event_type" ADD VALUE IF NOT EXISTS 'RESULT_CHECKPOINTED';
